// =============================================================================
// Map Definitions
// =============================================================================

export interface MapInfo {
  name: string;
  path: string;
}

export const MAPS: MapInfo[] = [
  { name: "凌绝峰连接地图", path: "/resources/map/map_001_凌绝峰连接地图.map" },
  { name: "凌绝峰峰顶", path: "/resources/map/map_002_凌绝峰峰顶.map" },
  { name: "武当山下", path: "/resources/map/map_003_武当山下.map" },
  { name: "武当山连接地图", path: "/resources/map/map_004_武当山连接地图.map" },
  { name: "洗剑池", path: "/resources/map/map_005_洗剑池.map" },
  { name: "武当山山顶", path: "/resources/map/map_006_武当山山顶.map" },
  { name: "连接地图 007", path: "/resources/map/map_007_连接地图.map" },
  { name: "野树林", path: "/resources/map/map_008_野树林.map" },
  { name: "山洞内部 009", path: "/resources/map/map_009_山洞内部.map" },
  { name: "山洞内部 010", path: "/resources/map/map_010_山洞内部.map" },
  { name: "连接地图 011", path: "/resources/map/map_011_连接地图.map" },
  { name: "惠安镇", path: "/resources/map/map_012_惠安镇.map" },
  { name: "连接地图 014", path: "/resources/map/map_014_连接地图.map" },
  { name: "藏剑山庄", path: "/resources/map/map_015_藏剑山庄.map" },
  { name: "剑气峰", path: "/resources/map/map_016_剑气峰.map" },
  { name: "连接地图 017", path: "/resources/map/map_017_连接地图.map" },
  { name: "连接地图 018", path: "/resources/map/map_018_连接地图.map" },
  { name: "寒波谷", path: "/resources/map/map_019_寒波谷.map" },
  { name: "寒波谷 (A)", path: "/resources/map/map_019_寒波谷(A).map" },
  { name: "寒波谷 (B)", path: "/resources/map/map_019_寒波谷(B).map" },
  { name: "樱花谷", path: "/resources/map/map_020_樱花谷.map" },
  { name: "油菜花地", path: "/resources/map/map_021_油菜花地.map" },
  { name: "清平乡", path: "/resources/map/map_022_清平乡.map" },
  { name: "连接地图 023", path: "/resources/map/map_023_连接地图.map" },
  { name: "倚天山", path: "/resources/map/map_024_倚天山.map" },
  { name: "摘星楼", path: "/resources/map/map_025_摘星楼.map" },
  { name: "摘星楼地下", path: "/resources/map/map_026_摘星楼地下.map" },
  { name: "连接地图 027", path: "/resources/map/map_027_连接地图.map" },
  { name: "连接地图 028", path: "/resources/map/map_028_连接地图.map" },
  { name: "码头", path: "/resources/map/map_029_码头.map" },
  { name: "悲魔山庄", path: "/resources/map/map_030_悲魔山庄.map" },
  { name: "连接地图 031", path: "/resources/map/map_031_连接地图.map" },
  { name: "天山", path: "/resources/map/map_032_天山.map" },
  { name: "落叶谷", path: "/resources/map/map_033_落叶谷.map" },
  { name: "落叶谷 (破坏后)", path: "/resources/map/map_033_落叶谷(破坏后).map" },
  { name: "天池", path: "/resources/map/map_034_天池.map" },
  { name: "天池内部", path: "/resources/map/map_035_天池内部.map" },
  { name: "连接地图 036", path: "/resources/map/map_036_连接地图.map" },
  { name: "敦煌十洞", path: "/resources/map/map_037_敦煌十洞.map" },
  { name: "连接地图 038", path: "/resources/map/map_038_连接地图.map" },
  { name: "飞龙堡", path: "/resources/map/map_039_飞龙堡.map" },
  { name: "沙漠", path: "/resources/map/map_040_沙漠.map" },
  { name: "通天塔一层", path: "/resources/map/MAP_041_通天塔一层.map" },
  { name: "通天塔二层", path: "/resources/map/MAP_042_通天塔二层.map" },
  { name: "通天塔第三层", path: "/resources/map/map_043_通天塔第三层.map" },
  { name: "通天塔四层", path: "/resources/map/MAP_044_通天塔四层.map" },
  { name: "通天塔第五层", path: "/resources/map/map_045_通天塔第五层.map" },
  { name: "通天塔第六层", path: "/resources/map/map_046_通天塔第六层.map" },
  { name: "通天塔第七层", path: "/resources/map/map_047_通天塔第七层.map" },
  { name: "通天塔第八层", path: "/resources/map/map_049_通天塔第八层.map" },
  { name: "忘忧岛", path: "/resources/map/map_050_忘忧岛.map" },
  { name: "海边", path: "/resources/map/map_051_海边.map" },
  { name: "码头 052", path: "/resources/map/map_052_码头.map" },
  { name: "连接地图 053", path: "/resources/map/map_053_连接地图.map" },
  { name: "北山", path: "/resources/map/map_054_北山.map" },
  { name: "山洞", path: "/resources/map/map_055_山洞.map" },
  { name: "盆地", path: "/resources/map/map_056_盆地.map" },
  { name: "盆地加坟墓", path: "/resources/map/map_056_盆地加坟墓.map" },
  { name: "连接地图 057", path: "/resources/map/map_057_连接地图.map" },
  { name: "禁地", path: "/resources/map/map_058_禁地.map" },
  { name: "禁地一层", path: "/resources/map/map_059_禁地一层.map" },
  { name: "禁地二层", path: "/resources/map/map_060_禁地二层.map" },
  { name: "禁地三层", path: "/resources/map/map_061_禁地三层.map" },
  { name: "禁地密室", path: "/resources/map/map_062_禁地密室.map" },
  { name: "药王谷", path: "/resources/map/map_063_药王谷.map" },
  { name: "霹雳堂", path: "/resources/map/map_064_霹雳堂.map" },
  { name: "霹雳堂被炸后", path: "/resources/map/map_064_霹雳堂被炸后.map" },
  { name: "天山古道", path: "/resources/map/map_065_天山古道.map" },
];
