/**
 * @miu2d/types - 共享类型定义
 *
 * 此包包含前后端共享的 Zod Schema 和 TypeScript 类型。
 */

export { UserSchema, UserSettingsSchema, UserSettingsPatchSchema } from "./user.js";
export type { User, UserSettings } from "./user.js";

export {
  GameSchema,
  CreateGameInputSchema,
  UpdateGameInputSchema,
  DeleteGameInputSchema
} from "./game.js";
export type {
  Game,
  CreateGameInput,
  UpdateGameInput,
  DeleteGameInput
} from "./game.js";

// 文件系统类型
export {
  FileTypeSchema,
  FileNodeSchema,
  ListFilesInputSchema,
  CreateFolderInputSchema,
  PrepareUploadInputSchema,
  PrepareUploadOutputSchema,
  ConfirmUploadInputSchema,
  GetDownloadUrlInputSchema,
  GetDownloadUrlOutputSchema,
  GetUploadUrlInputSchema,
  GetUploadUrlOutputSchema,
  RenameFileInputSchema,
  MoveFileInputSchema,
  DeleteFileInputSchema,
  GetFilePathInputSchema,
  PathNodeSchema,
  GetFilePathOutputSchema,
  BatchPrepareUploadFileSchema,
  BatchPrepareUploadInputSchema,
  BatchPrepareUploadResultSchema,
  BatchPrepareUploadOutputSchema,
  BatchConfirmUploadInputSchema,
  BatchConfirmUploadOutputSchema,
  EnsureFolderPathInputSchema,
  EnsureFolderPathOutputSchema
} from "./file.js";
export type {
  FileType,
  FileNode,
  ListFilesInput,
  CreateFolderInput,
  PrepareUploadInput,
  PrepareUploadOutput,
  ConfirmUploadInput,
  GetDownloadUrlInput,
  GetDownloadUrlOutput,
  GetUploadUrlInput,
  GetUploadUrlOutput,
  RenameFileInput,
  MoveFileInput,
  DeleteFileInput,
  GetFilePathInput,
  PathNode,
  GetFilePathOutput,
  BatchPrepareUploadInput,
  BatchPrepareUploadOutput,
  BatchConfirmUploadInput,
  BatchConfirmUploadOutput,
  EnsureFolderPathInput,
  EnsureFolderPathOutput
} from "./file.js";

// 武功类型
export {
  MagicMoveKindEnum,
  MagicMoveKindValues,
  MagicMoveKindFromValue,
  MagicMoveKindLabels,
  MagicSpecialKindEnum,
  MagicSpecialKindValues,
  MagicSpecialKindFromValue,
  MagicSpecialKindLabels,
  MagicUserTypeEnum,
  MagicBelongEnum,
  MagicBelongValues,
  MagicBelongFromValue,
  MagicBelongLabels,
  MagicRegionTypeEnum,
  MagicRegionTypeValues,
  MagicRegionTypeFromValue,
  MagicRegionTypeLabels,
  MagicLevelSchema,
  MagicBaseSchema,
  MagicSchema,
  MagicListItemSchema,
  CreateMagicInputSchema,
  UpdateMagicInputSchema,
  DeleteMagicInputSchema,
  ListMagicInputSchema,
  ImportMagicInputSchema,
  BatchImportMagicItemSchema,
  BatchImportMagicInputSchema,
  BatchImportMagicResultSchema,
  GetMagicInputSchema,
  AttackFileSchema,
  getVisibleFieldsByMoveKind,
  createDefaultLevels,
  createDefaultMagic,
  createDefaultAttackFile,
} from "./magic.js";
export type {
  MagicMoveKind,
  MagicSpecialKind,
  MagicUserType,
  MagicBelong,
  MagicRegionType,
  MagicLevel,
  MagicBase,
  Magic,
  MagicListItem,
  CreateMagicInput,
  UpdateMagicInput,
  DeleteMagicInput,
  ListMagicInput,
  ImportMagicInput,
  BatchImportMagicItem,
  BatchImportMagicInput,
  BatchImportMagicResult,
  GetMagicInput,
  AttackFile,
} from "./magic.js";
// 等级配置类型
export {
  LevelUserTypeEnum,
  LevelDetailSchema,
  LevelConfigSchema,
  LevelConfigListItemSchema,
  ListLevelConfigInputSchema,
  GetLevelConfigInputSchema,
  CreateLevelConfigInputSchema,
  UpdateLevelConfigInputSchema,
  DeleteLevelConfigInputSchema,
  ImportLevelConfigInputSchema,
  createDefaultLevelDetail,
  createDefaultLevels as createDefaultLevelConfigLevels,
  createDefaultLevelConfig,
} from "./level.js";
export type {
  LevelUserType,
  LevelDetail,
  LevelConfig,
  LevelConfigListItem,
  ListLevelConfigInput,
  GetLevelConfigInput,
  CreateLevelConfigInput,
  UpdateLevelConfigInput,
  DeleteLevelConfigInput,
  ImportLevelConfigInput,
} from "./level.js";

// 物品类型
export {
  GoodsKindEnum,
  GoodsKindValues,
  GoodsKindFromValue,
  GoodsKindLabels,
  GoodsPartEnum,
  GoodsPartLabels,
  GoodsEffectTypeEnum,
  GoodsEffectTypeLabels,
  getActualEffectType,
  getEffectTypeOptions,
  ConsumableDataSchema,
  EquipmentDataSchema,
  QuestDataSchema,
  GoodsSchema,
  GoodsListItemSchema,
  ListGoodsInputSchema,
  GetGoodsInputSchema,
  CreateGoodsInputSchema,
  UpdateGoodsInputSchema,
  DeleteGoodsInputSchema,
  ImportGoodsInputSchema,
  BatchImportGoodsItemSchema,
  BatchImportGoodsInputSchema,
  BatchImportGoodsResultSchema,
  getVisibleFieldsByKind,
  createDefaultGoods,
} from "./goods.js";
export type {
  GoodsKind,
  GoodsPart,
  GoodsEffectType,
  ConsumableData,
  EquipmentData,
  QuestData,
  Goods,
  GoodsListItem,
  ListGoodsInput,
  GetGoodsInput,
  CreateGoodsInput,
  UpdateGoodsInput,
  DeleteGoodsInput,
  ImportGoodsInput,
  BatchImportGoodsItem,
  BatchImportGoodsInput,
  BatchImportGoodsResult,
} from "./goods.js";

// 游戏全局配置类型
export {
  MoneyDropTierSchema,
  DrugDropTierSchema,
  DropProbabilitySchema,
  BossLevelBonusSchema,
  EquipDropTierSchema,
  DropConfigSchema,
  PlayerInitialStatsSchema,
  PlayerThewCostSchema,
  PlayerRestoreSchema,
  PlayerSpeedSchema,
  PlayerCombatSchema,
  PlayerConfigSchema,
  GameConfigDataSchema,
  GameConfigSchema,
  GetGameConfigInputSchema,
  UpdateGameConfigInputSchema,
  createDefaultDropConfig,
  createDefaultPlayerConfig,
  createDefaultGameConfig,
  mergeGameConfig,
} from "./gameConfig.js";
export type {
  MoneyDropTier,
  DrugDropTier,
  DropProbability,
  BossLevelBonus,
  EquipDropTier,
  DropConfig,
  PlayerInitialStats,
  PlayerThewCost,
  PlayerRestore,
  PlayerSpeed,
  PlayerCombat,
  PlayerConfig,
  GameConfigData,
  GameConfigDataFull,
  GameConfig,
  GetGameConfigInput,
  UpdateGameConfigInput,
} from "./gameConfig.js";

// 商店类型
export {
  ShopItemSchema,
  ShopSchema,
  ShopListItemSchema,
  ListShopInputSchema,
  GetShopInputSchema,
  CreateShopInputSchema,
  UpdateShopInputSchema,
  DeleteShopInputSchema,
  ImportShopInputSchema,
  BatchImportShopItemSchema,
  BatchImportShopInputSchema,
  BatchImportShopResultSchema,
  createDefaultShop,
} from "./shop.js";
export type {
  ShopItem,
  Shop,
  ShopListItem,
  ListShopInput,
  GetShopInput,
  CreateShopInput,
  UpdateShopInput,
  DeleteShopInput,
  ImportShopInput,
  BatchImportShopItem,
  BatchImportShopInput,
  BatchImportShopResult,
} from "./shop.js";

// NPC 类型
export {
  NpcKindEnum,
  NpcKindValues,
  NpcKindFromValue,
  NpcKindLabels,
  NpcRelationEnum,
  NpcRelationValues,
  NpcRelationFromValue,
  NpcRelationLabels,
  NpcStateEnum,
  NpcStateLabels,
  NpcStateResourceSchema,
  NpcResourceSchema,
  NpcBaseSchema,
  NpcSchema,
  NpcResSchema,
  NpcResListItemSchema,
  NpcAppearanceSchema,
  NpcAppearanceListItemSchema,
  NpcListItemSchema,
  ListNpcInputSchema,
  GetNpcInputSchema,
  CreateNpcInputSchema,
  UpdateNpcInputSchema,
  DeleteNpcInputSchema,
  ListNpcResInputSchema,
  GetNpcResInputSchema,
  CreateNpcResInputSchema,
  UpdateNpcResInputSchema,
  DeleteNpcResInputSchema,
  ListNpcAppearanceInputSchema,
  GetNpcAppearanceInputSchema,
  CreateNpcAppearanceInputSchema,
  UpdateNpcAppearanceInputSchema,
  DeleteNpcAppearanceInputSchema,
  ImportNpcItemSchema,
  ImportNpcInputSchema,
  BatchImportNpcInputSchema,
  BatchImportNpcResultSchema,
  createDefaultNpc,
  createDefaultNpcResource,
  getVisibleFieldsByNpcKind,
  npcStateToResourceKey,
  // 资源路径规范化
  NpcResourcePaths,
  normalizeNpcImagePath,
  normalizeNpcSoundPath,
  normalizeNpcResourcePaths,
} from "./npc.js";
export type {
  NpcKind,
  NpcRelation,
  NpcState,
  NpcStateResource,
  NpcResource,
  NpcBase,
  Npc,
  NpcRes,
  NpcResListItem,
  NpcAppearance,
  NpcAppearanceListItem,
  NpcListItem,
  ListNpcInput,
  GetNpcInput,
  CreateNpcInput,
  UpdateNpcInput,
  DeleteNpcInput,
  ListNpcResInput,
  GetNpcResInput,
  CreateNpcResInput,
  UpdateNpcResInput,
  DeleteNpcResInput,
  ListNpcAppearanceInput,
  GetNpcAppearanceInput,
  CreateNpcAppearanceInput,
  UpdateNpcAppearanceInput,
  DeleteNpcAppearanceInput,
  ImportNpcItem,
  ImportNpcInput,
  BatchImportNpcInput,
  BatchImportNpcResult,
} from "./npc.js";

// 玩家角色类型
export {
  PlayerInitialMagicSchema,
  PlayerInitialGoodsSchema,
  PlayerBaseSchema,
  PlayerSchema,
  PlayerListItemSchema,
  ListPlayerInputSchema,
  GetPlayerInputSchema,
  CreatePlayerInputSchema,
  UpdatePlayerInputSchema,
  DeletePlayerInputSchema,
  ImportPlayerInputSchema,
  BatchImportPlayerItemSchema,
  BatchImportPlayerInputSchema,
  BatchImportPlayerResultSchema,
  createDefaultPlayer,
} from "./player.js";
export type {
  PlayerInitialMagic,
  PlayerInitialGoods,
  PlayerBase,
  Player,
  PlayerListItem,
  ListPlayerInput,
  GetPlayerInput,
  CreatePlayerInput,
  UpdatePlayerInput,
  DeletePlayerInput,
  ImportPlayerInput,
  BatchImportPlayerInput,
  BatchImportPlayerResult,
} from "./player.js";

// 对话头像映射类型
export {
  PortraitEntrySchema,
  PortraitMapSchema,
  PortraitMapResultSchema,
  GetPortraitMapInputSchema,
  UpdatePortraitMapInputSchema,
  ImportPortraitMapInputSchema,
  parsePortraitIni,
  exportPortraitIni,
} from "./talkPortrait.js";
export type {
  PortraitEntry,
  PortraitMap,
  PortraitMapResult,
  GetPortraitMapInput,
  UpdatePortraitMapInput,
  ImportPortraitMapInput,
} from "./talkPortrait.js";

// Object 类型
export {
  ObjKindEnum,
  ObjKindValues,
  ObjKindFromValue,
  ObjKindLabels,
  ObjResStateEnum,
  ObjResStateLabels,
  // 兼容别名
  ObjStateEnum,
  ObjStateLabels,
  ObjStateResourceSchema,
  ObjResourceSchema,
  ObjResSchema,
  ObjResListItemSchema,
  ObjBaseSchema,
  ObjSchema,
  ObjListItemSchema,
  ListObjInputSchema,
  GetObjInputSchema,
  CreateObjInputSchema,
  UpdateObjInputSchema,
  DeleteObjInputSchema,
  // Object 资源 API
  ListObjResInputSchema,
  GetObjResInputSchema,
  CreateObjResInputSchema,
  UpdateObjResInputSchema,
  DeleteObjResInputSchema,
  // 导入
  ImportObjItemSchema,
  ImportObjInputSchema,
  BatchImportObjInputSchema,
  BatchImportObjResultSchema,
  createDefaultObj,
  createDefaultObjRes,
  createDefaultObjResource,
  getVisibleFieldsByObjKind,
  // 资源路径规范化
  ObjResourcePaths,
  normalizeObjImagePath,
  normalizeObjSoundPath,
  normalizeObjResourcePaths,
} from "./obj.js";
export type {
  ObjKind,
  ObjResState,
  // 兼容别名
  ObjState,
  ObjStateResource,
  ObjResource,
  ObjRes,
  ObjResListItem,
  ObjBase,
  Obj,
  ObjListItem,
  ListObjInput,
  GetObjInput,
  CreateObjInput,
  UpdateObjInput,
  DeleteObjInput,
  ListObjResInput,
  GetObjResInput,
  CreateObjResInput,
  UpdateObjResInput,
  DeleteObjResInput,
  ImportObjItem,
  ImportObjInput,
  BatchImportObjInput,
  BatchImportObjResult,
} from "./obj.js";

// --- talk ---
export {
  TalkEntrySchema, TalkDataSchema,
  GetTalkDataInputSchema, UpdateTalkDataInputSchema, ImportTalkDataInputSchema,
  TalkDataResultSchema,
  CreateTalkEntryInputSchema, UpdateTalkEntryInputSchema, DeleteTalkEntryInputSchema,
  SearchTalkInputSchema, SearchTalkResultSchema,
  parseTalkIndexTxt, exportTalkIndexTxt, extractSpeakerName,
} from "./talk.js";
export type {
  TalkEntry, TalkData,
  GetTalkDataInput, UpdateTalkDataInput, ImportTalkDataInput, TalkDataResult,
  CreateTalkEntryInput, UpdateTalkEntryInput, DeleteTalkEntryInput,
  SearchTalkInput, SearchTalkResult,
} from "./talk.js";

// 存档类型
export {
  SaveSlotSchema,
  UpsertSaveInputSchema,
  ListSavesInputSchema,
  GetSaveInputSchema,
  DeleteSaveInputSchema,
  ShareSaveInputSchema,
  GetSharedSaveInputSchema,
  SaveDataResponseSchema,
  AdminListSavesInputSchema,
  AdminListSavesOutputSchema,
  AdminCreateSaveInputSchema,
  AdminDeleteSaveInputSchema,
} from "./save.js";
export type {
  SaveSlot,
  UpsertSaveInput,
  ListSavesInput,
  GetSaveInput,
  DeleteSaveInput,
  ShareSaveInput,
  GetSharedSaveInput,
  SaveDataResponse,
  AdminListSavesInput,
  AdminListSavesOutput,
  AdminCreateSaveInput,
  AdminDeleteSaveInput,
} from "./save.js";